### ISSUE TITLE
important math bugs

### ISSUE THREAD

**Issue by cben** [cben/mathdown#106]
- [ ] $x_y$ should not make the rest of the line italic [https://github.com/cben/CodeMirror-MathJax/issues/4]
- [ ] Edit formula on click [https://github.com/cben/CodeMirror-MathJax/issues/9]
- [ ] unrendering/rerendering is flaky [https://github.com/cben/CodeMirror-MathJax/issues/23]

Would be great to do https://github.com/cben/CodeMirror-MathJax/issues/13 and everything following from it, especially:
- [ ] multi-line equations [https://github.com/cben/CodeMirror-MathJax/issues/3]

but that's less urgent.

**Comment by cben** [comment]
Also consider performance:
- [ ] KaTeX [https://github.com/cben/CodeMirror-MathJax/issues/39]

and/or
- [x] MathJax 2.5 [https://github.com/cben/CodeMirror-MathJax/issues/33]

**Comment by cben** [comment]
New MathJax finally addressed by #169
