### ISSUE TITLE
Move to Gitlab Pages?

### ISSUE THREAD

**Issue by cben** [cben/mathdown#174]
Per #172, to make progress and ensure project logevity, I want to reduce operational complexity by switching to static hosting.  Gitlab Pages seems near-perfect with TLS support and FOSS implementation.

- [ ] is redirect to HTTPS possible yet? https://gitlab.com/gitlab-org/gitlab-ce/issues/28857
  - client-side JS redirect less attractive, want to avoid http links to mathdown getting any link juice...
  - is http equiv meta tag better?

- [ ] how to deploy Let's Encrypt certs?  For now there's no automation nor API (https://gitlab.com/gitlab-org/gitlab-ce/issues/28996),  so manually via web UI.

- [ ] is HSTS possible?  (https://gitlab.com/gitlab-org/gitlab-pages/issues/28)

**Comment by cben** [comment]
Closing, I'm moving to Netlify instead, their preview-env-for-each-PR is great.
