### ISSUE TITLE
Site checklist

### ISSUE THREAD

**Issue by cben** [cben/mathdown#25]
http://webdevchecklist.com/

**Comment by cben** [comment]
Points from [Modern.IE static scan](http://www.modern.ie/en-us/report#http%3A%2F%2Fmathdown.net), not all relevant:
- [ ] Responsive web design
  - [ ] Test at least reading on smartphone
- [ ] Browser detection (all justified by IE bugs, thank you very much – codemirror, mathjax, firebase, firepad)
- [ ] [Prerender and Prefetch](http://msdn.microsoft.com/en-us/library/ie/dn265039%28v=vs.85%29.aspx)
- [ ] Touch-first browsing
  - [ ] Check if CodeMirror supports touch scrolling
- [ ] [Flip ahead browsing](http://msdn.microsoft.com/en-us/library/ie/jj883726%28v=vs.85%29.aspx)
- [ ] [IE11 tiles and notifications](http://www.buildmypinnedsite.com/en)

**Comment by cben** [comment]
http://keepwomen.com/static_pages/checklist_tool
